#!/usr/bin/env ruby

require 'erb'
require 'fileutils'

FileUtils.chdir(File.dirname(__FILE__))

## For OSX:
ENV['PATH'] = "#{ENV['PATH']}:/usr/libexec"

template = File.read('slapd-test.conf.erb')
normal_out = 'slapd-test.conf'
ssl_out = 'slapd-ssl-test.conf'

File.open(normal_out, 'w') do |f|
  @ssl = false
  f.write ERB.new(template).result(binding)
end
File.open(ssl_out, 'w') do |f|
  @ssl = true
  f.write ERB.new(template).result(binding)
end

config_file = if ARGV.first == '--ssl'
  ssl_out
else
  normal_out
end

cmd = "slapd -d 1 -f %s -h 'ldap://localhost:3389 ldap://localhost:3390'" % config_file
puts(cmd)
exec(cmd)
